language: python

services:
  - docker

install:
  - docker-compose up --build -d

before_script:
  - python postgres_monitor.py
  - docker exec -it django python manage.py makemigrations
  - docker exec -it django python manage.py migrate

script:
  - docker exec -it django python manage.py test
