language: python

services:
  - docker

install:
  - python -m pip install docker
  - docker-compose up --build -d

before_script:
  - python postgres_monitor.py
  - docker exec -it django python manage.py makemigrations
  - docker exec -it django python manage.py migrate

script:
  - docker exec -it django pytest

deploy:
  provider: script
  script: python build_lift_container
  on:
    branch: push_docker_image
