language: python

services:
  - docker

env:
  - DJANGO_SETTINGS_MODULE='lift.settings'

install:
  - python -m pip install docker
  - docker-compose up --build -d

before_script:
  - python postgres_monitor.py
  - docker exec -it django python manage.py makemigrations
  - docker exec -it django python manage.py migrate

script:
  - echo $DJANGO_SETTINGS_MODULE
  - cat pytest.ini
  - docker exec -it django pytest --cov
  - docker cp django:code/.coverage ./
  - sed -i "s@\"/code/@\"${PWD}/@g" .coverage

after_success:
  - python -m pip install coveralls==1.8.2
  - coveralls

deploy:
  skip_cleanup: true
  provider: script
  script: python build_lift_container.py --repo $docker_repo --user $docker_username --passwd $docker_password
  on:
    branch: release
