language: python

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.18.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - python -m pip install docker
  - docker-compose up --build -d
  - docker logs postgres

before_script:
  - python postgres_monitor.py
  - docker exec -it django python manage.py makemigrations
  - docker exec -it django python manage.py migrate

script:
  - docker exec -it django pytest --cov
  - docker cp django:code/.coverage ./
  - sed -i "s@\"/code/@\"${PWD}/@g" .coverage

after_success:
  - python -m pip install coveralls
  - coveralls

deploy:
  provider: script
  script: python build_lift_container.py --repo $docker_repo --user $docker_username --passwd $docker_password
  on:
    branch: master
