language: python

services:
  - docker

before_script:
  - docker-compose up --build -d
  - docker exec -it django python manage.py makemigrations
  - docker exec -it django python manage.py migrate

script:
  - docker exec -it django python manage.py test
