language: python

services:
  - docker

before_script:
  - docker-compose up --build -d
  - docker exec -it django bash
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - docker exec -it django bash
  - python manage.py test
