language: python

services:
  - docker

before_script:
  - docker-compose up --build

script:
  - docker exec -it django python manage.py makemigrations
  - docker exec -it django python manage.py migrate
  - docker exec -it django python manage.py test
