version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    
  web:
    restart: always
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data: