version: '3'

services:
  db:
    image: postgres:11.7
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - "5555:5432"
    environment: 
      POSTGRES_HOST_AUTH_METHOD: trust
    
  web:
    restart: always
    build: .
    container_name: django
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    networks:
      - internal
    environment:
      DJANGO_SETTINGS_MODULE: 'lift.settings'
    command: gunicorn lift.wsgi:application --bind 0.0.0.0:8000

volumes:
  db-data:

networks:
  internal:
    driver: bridge