version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - internal
    depends_on:
      - web
    restart: always

  web:
    restart: always
    build: .
    container_name: django
    volumes:
      - .:/code
    depends_on:
      - "db"
    networks:
      - internal
    environment:
      DJANGO_SETTINGS_MODULE: 'lift.settings'
    command: gunicorn lift.wsgi:application --bind 0.0.0.0:8000

  db:
    image: postgres:11.7
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - "5555:5432"
    environment: 
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  db-data:

networks:
  internal:
    driver: bridge